---
- name: STAGE | Add users
  include_tasks: tasks/add-users.yml

- name: STAGE | Setup Firewall
  include_tasks: tasks/setup-fw.yml

- name: STAGE | Add Firewall-restore service
  include_tasks: tasks/setup-fw-restore.yml

- name: STAGE | Setup Fail2Ban service
  include_tasks: tasks/setup-f2b.yml

- name: STAGE | Setup Nginx and deploy site-content
  include_tasks: tasks/setup-webserver.yml
