---
- name: Install ipset if it's not installed
  apt:
    name: ipset
    state: present
    update_cache: true

- name: Copy ipset-whitelist.conf
  template:
    src: ipset-whitelist.conf.j2
    dest: /etc/ipset-whitelist.conf

- name: Restore ipset
  command: ipset restore -file /etc/ipset-whitelist.conf

- name: Install iptables if it's not installed
  apt:
    name: iptables
    state: present
    update_cache: true

- name: Copy iptables rules
  copy:
    src: files/iptables
    dest: /etc/iptables.rules

- name: Restore iptables
  shell: iptables-restore < /etc/iptables.rules
