---
- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
    update_cache: true

- name: Setup fail2ban
  copy:
    src: files/jail_local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: Restart fail2ban
