- name: Restart fail2ban
  systemd:
    name: fail2ban
    state: restarted
    enabled: true

- name: Reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: Restart ssh
  systemd:
    name: ssh
    state: restarted
